(()=>{'use strict';const A=QuoteCore,P=QuotePDF,$=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let store,storageOK=true;try{store=new A.Store(localStorage);localStorage.setItem('navbharat.probe','1');localStorage.removeItem('navbharat.probe');}catch(e){storageOK=false;store=new A.Store({getItem:()=>null,setItem:()=>{}});}
const app=window.App={store,quote:store.state.draft||store.create(),step:0,view:'history',settings:null,render};A.ensureEquipmentState(app.quote);
let notificationTimer=null;
function clearNotification(){if(notificationTimer!==null)window.clearTimeout(notificationTimer);notificationTimer=null;$('status').textContent='';$('status').className='';}
function notify(text,error=false){clearNotification();$('status').textContent=text;$('status').className=error?'error':'success';if(!error){const timer=window.setTimeout(()=>{if(notificationTimer===timer)clearNotification();},4000);notificationTimer=timer;}}
function guard(fn){try{fn();}catch(e){notify(e.message,true);}}
function saveDraft(){try{store.draft(app.quote);if(storageOK)document.querySelectorAll('.panel-save,.task-save').forEach(el=>el.textContent='Saved');}catch(e){storageOK=false;document.querySelectorAll('.panel-save,.task-save').forEach(el=>el.textContent='Not saved · session only');notify('Draft could not be saved. Download a backup now. '+e.message,true);}}
function input(label,id,value,type='text',path=id,wide=false){return `<label class="field ${wide?'wide':''}" for="${id}"><span>${esc(label)}</span>${type==='textarea'?`<textarea id="${id}" data-path="${path}" rows="3">${esc(value)}</textarea>`:`<input id="${id}" data-path="${path}" type="${type}" ${type==='number'?'step="any" min="0" inputmode="decimal"':''} value="${esc(value)}">`}</label>`;}
const button=(id,text,cls='')=>`<button type="button" id="${id}" class="${cls}">${text}</button>`;
function setPath(obj,path,value){const parts=path.split('.');const last=parts.pop();let target=obj;parts.forEach(p=>target=target[p]);target[last]=value;}
function fitTextarea(e){e.style.height='auto';e.style.height=Math.max(44,e.scrollHeight+2)+'px';}
window.addEventListener('resize',()=>document.querySelectorAll('[data-autogrow]').forEach(fitTextarea));
function fieldEvents(obj){document.querySelectorAll('[data-autogrow]').forEach(fitTextarea);document.querySelectorAll('[data-path]').forEach(e=>{if(e.dataset.bound)return;e.dataset.bound='true';e.addEventListener(e.type==='checkbox'?'change':'input',()=>{if(e.disabled)return;const value=e.type==='checkbox'?e.checked:e.type==='number'?(e.value===''?'':Number(e.value)):e.value;let previous=null;if(obj===app.quote&&e.dataset.path.startsWith('equipment.')&&e.type==='checkbox'){const g=obj.equipment[Number(e.dataset.path.split('.')[1])];previous={enabled:g.enabled,items:g.items.map(i=>i.enabled)};if(!g.enabled){g.items.forEach(i=>i.enabled=false);g.enabled=true;}}setPath(obj,e.dataset.path,value);if(obj===app.quote&&e.dataset.path.startsWith('equipment.')&&e.type==='checkbox')offerEquipmentUndo(e.dataset.path,previous);if(e.hasAttribute('data-autogrow'))fitTextarea(e);if(e.dataset.path.startsWith('equipment.'))equipmentAppearance(obj);if(obj===app.quote){if(e.dataset.path!=='referenceReviewed')obj.referenceReviewed=false;if(e.dataset.path==='cost'&&value!==''&&Number(value)>0)A.acknowledgePrice(obj);saveDraft();updateAmounts();updatePriceReminder();}else if(e.dataset.path.startsWith('company.')&&e.dataset.path!=='company.bankVerified'){obj.company.bankVerified=false;const c=$('bankVerified');if(c)c.checked=false;}});});}
function priceReminder(){return `<aside id="price-reminder" class="notice price-reminder" ${A.priceNeedsReview(app.quote)?'':'hidden'}><b>Check total price</b><p>Equipment or capacity changed. Check the quoted total; the existing price may still be valid. Nothing is priced automatically.</p>${button('price-checked','I checked — current total is valid','secondary')}</aside>`;}
function updatePriceReminder(){document.querySelectorAll('.panel-price-hint').forEach(el=>el.hidden=!A.priceNeedsReview(app.quote));if($('price-reminder'))$('price-reminder').hidden=!A.priceNeedsReview(app.quote);}
function offerEquipmentUndo(path,previous){app.equipmentUndo={path,previous};document.querySelector('#equipment-undo')?.remove();const host=document.createElement('div');host.id='equipment-undo';host.className='equipment-undo';host.setAttribute('role','status');host.innerHTML=`<span>${app.quote.equipment[Number(path.split('.')[1])].items[Number(path.split('.')[3])].enabled?'Item restored to quotation.':'Item excluded from quotation.'}</span>${button('undo-equipment','Undo','secondary')}`;const panel=$('equipment-panel');(panel||document.querySelector('.scope-overview')).append(host);$('undo-equipment').onclick=()=>{const gi=Number(path.split('.')[1]),g=app.quote.equipment[gi];g.enabled=previous.enabled;g.items.forEach((i,ii)=>{if(previous.items[ii]!==undefined)i.enabled=previous.items[ii];});document.querySelectorAll(`input[data-path^="equipment.${gi}.items."]`).forEach(control=>{const ii=Number(control.dataset.path.split('.')[3]);control.checked=g.enabled&&g.items[ii].enabled;});app.quote.referenceReviewed=false;saveDraft();quoteEquipmentAppearance();updatePriceReminder();host.remove();};}
function updateAmounts(){if($('net-value'))$('net-value').textContent=P.money(A.amounts(app.quote).net);if($('vendor-value'))$('vendor-value').textContent=P.money(app.quote.cost);}
function nav(view){clearNotification();if(app.editor)closeEquipmentPanel();saveDraft();app.view=view;if(view==='settings')app.settings=A.clone(store.state.settings);render();if(window.scrollY)window.scrollTo(0,0);}
function quoteHelp(){const copy=["Enter the customer name, address and quotation details for this lead, then select Continue. Changes save on this device as you type.","Enter the system capacity, total price and estimated subsidy for this lead. Standard equipment is ready below. Use the pencil Edit action beside any equipment category to change quantities or inclusion. Pencil Edit details opens the specification and warranty. The switch includes or excludes an item without deleting its details. Equipment is not priced automatically. Update the total price manually only if needed, or confirm the current total is valid, then continue to Review.","Check the customer details, equipment quantities, total price and payment percentages. Confirm the review checkbox before saving or viewing the PDF. Check the preview, then download a copy when ready."];return `<details id="quote-help" class="operator-help task-help"><summary>Help</summary><p>${copy[app.step]}</p></details>`;}
function startNewQuote(){guard(()=>{if(confirm('Start a new quotation? The current draft will be replaced. Saved quotations will remain.')){app.quote=store.create();app.step=0;nav('quote');}});}
let stickyHeaderObserver=null;
function updateTaskHeaderHeight(){const header=document.querySelector('.task-sticky'),height=header?.getBoundingClientRect().height;const style=document.documentElement.style;if(height)style.setProperty('--quotation-header-height',`${height}px`);else style.removeProperty('--quotation-header-height');}
function syncTaskHeader(){if(stickyHeaderObserver){stickyHeaderObserver.disconnect();stickyHeaderObserver=null;}updateTaskHeaderHeight();const header=document.querySelector('.task-sticky');if(header&&typeof ResizeObserver==='function'){stickyHeaderObserver=new ResizeObserver(updateTaskHeaderHeight);stickyHeaderObserver.observe(header);}}
window.addEventListener('resize',updateTaskHeaderHeight);
function render(){const editing=app.view==='quote';$('app').classList.toggle('focused-task',editing);$('app').innerHTML=`${editing?`<div class="task-sticky"><header class="task-header">${button('nav-history','← Quotations','task-exit')}<span class="task-save" role="status">${storageOK?'Saved':'Not saved · session only'}</span></header>${taskHeading()}</div>`:`<header class="workspace-header"><a class="brand" href="#" id="brand" aria-label="Nav Bharat Enterprises — Quotations home"><svg class="brand-symbol" viewBox="0 0 44 44" aria-hidden="true" focusable="false"><circle cx="32" cy="10" r="5" fill="var(--gold)"/><path d="M32 2V1M40 10h2M38 4l1-1" fill="none" stroke="var(--gold)" stroke-width="1.8" stroke-linecap="round"/><path d="M4 21 27 15 39 30 16 36Z" fill="currentColor"/><path d="m12 19 12 15m-4-17 12 15M9 27l23-6" fill="none" stroke="var(--cream)" stroke-width="1.2"/><path d="M15 37v4m18-8v8M10 41h28" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg><span class="brand-wordmark"><span class="brand-name">Nav Bharat</span><span class="brand-descriptor">Enterprises</span></span></a>${app.view==='history'?button('nav-settings','Configure','quiet'):`${button('nav-history','← Quotations','quiet')}${button('nav-quote','Resume draft','quiet')}`}</header>`}${editing?wizard():app.view==='history'?history():settings()}${editing?'':`<footer class="app-footer">NAV BHARAT ENTERPRISES <span>Offline · ${storageOK?'Saved on this device':'Session only · Not saved'} · No cloud sync</span></footer>`}`;
if($('brand'))$('brand').onclick=e=>{e.preventDefault();nav('history');};if($('nav-quote'))$('nav-quote').onclick=()=>nav('quote');if($('nav-history'))$('nav-history').onclick=()=>nav('history');if($('nav-settings'))$('nav-settings').onclick=()=>nav('settings');if($('new'))$('new').onclick=startNewQuote;if(editing)bindQuote();else if(app.view==='history')bindHistory();else bindSettings();syncTaskHeader();}
function taskHeading(){const titles=['Customer details','System & pricing','Review & download'];return `<section class="task-heading"><h1>${titles[app.step]}</h1><div class="task-meta"><p id="step-progress">Step ${app.step+1} of 3</p>${quoteHelp()}</div><div class="task-progress" role="progressbar" aria-label="Quotation steps" aria-valuemin="1" aria-valuemax="3" aria-valuenow="${app.step+1}" aria-valuetext="Step ${app.step+1} of 3: ${titles[app.step]}">${titles.map((_,i)=>`<span aria-hidden="true" class="task-progress-segment ${i<app.step?'is-earlier':i===app.step?'is-current':'is-upcoming'}"></span>`).join('')}</div></section>`;}
function wizard(){return `<div class="workspace">${app.step===0?customer():app.step===1?system():review()}<div class="wizard-actions task-actions">${app.step>0?button('back','← Back','task-back'):'<span class="draft-caption">Draft saved as you type</span>'}${app.step<2?button('next','Continue →','primary'):`<div class="action-group">${button('save','Save quotation','secondary')}${button('pdf','View PDF','primary')}</div>`}</div></div>`;}
function customer(){const q=app.quote;return `<section class="card"><div class="section-heading"><span class="section-number">01</span><div><h2>Customer details</h2><p>Use the applicant details shown on their documents.</p></div></div><div class="fields">${input('Customer name *','customer-name',q.customer.name,'text','customer.name')}${input('Mobile / WhatsApp','customer-phone',q.customer.phone,'tel','customer.phone')}${input('Address *','customer-address',q.customer.address,'textarea','customer.address',true)}${input('Email (optional)','customer-email',q.customer.email,'email','customer.email')}${input('Electricity consumer number','customer-consumer',q.customer.consumer,'text','customer.consumer')}</div></section><section class="card"><h2>Quotation details</h2><div class="fields">${input('Quotation number *','number',q.number)}${input('Quotation date *','date',q.date,'date')}${input('Validity (days)','validity',q.validity,'number')}</div><p class="muted">Numbers are reserved sequentially on this device. Unsaved drafts may leave gaps.</p></section>`;}
function detailsFields(q){return `<div class="fields">${input('Estimated annual generation','generation',q.generation)}${input('System life','life',q.life)}${input('Maintenance','maintenance',q.maintenance)}${input('Required customer documents','documents',q.documents,'textarea','documents',true)}${input('Terms and conditions','terms',q.terms,'textarea','terms',true)}</div>`;}
function ambiguousQuantity(value){return /^\s*\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?(?:\s+.*)?\s*$/.test(value);}
function panelMarkup(){const e=app.editor,g=app.quote.equipment[e.gi];return `<div id="equipment-panel" class="equipment-panel" role="dialog" aria-modal="true" aria-labelledby="equipment-panel-title"><header class="panel-header"><div class="panel-navigation"><button type="button" id="equipment-back" class="panel-back" aria-label="${e.ii!==null&&e.fromGroup?'Back to quantities':'Back to quotation'}">← Back</button><p class="panel-save" role="status">${storageOK?'Saved':'Not saved · session only'}</p></div><h2 id="equipment-panel-title">${esc(g.name)}</h2></header><div class="panel-body">${e.ii===null?`${g.items.map((item,ii)=>`<article class="scope-editor-item ${g.enabled&&item.enabled?'':'is-excluded'}" data-item="${ii}"><div class="scope-item-header"><h3>${esc(item.description||'Custom item')}</h3>${inclusionField(e.gi,ii,item)}</div><div class="scope-item-fields">${quantityField(e.gi,ii,item)}<button type="button" id="spec-item-${e.gi}-${ii}" class="item-details-edit" ${g.enabled&&item.enabled?'':'disabled'} aria-label="Edit details: ${esc(item.description||'Custom item')}"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m16 3 5 5-12 12-6 1 1-6Z"/><path d="m14 5 5 5"/></svg><span>Edit details</span></button></div></article>`).join('')}${button('add-custom-item','+ Add item','panel-add')}`:`<p class="eyebrow">ITEM ${e.ii+1} · SPECIFICATION</p><h3>${esc(g.items[e.ii].description||'Custom item')}</h3>${input('Item / specification',e.ii===0?`row-description-${e.gi}`:`item-description-${e.gi}-${e.ii}`,g.items[e.ii].description,'textarea',`equipment.${e.gi}.items.${e.ii}.description`,true)}${input('Warranty',e.ii===0?`row-warranty-${e.gi}`:`item-warranty-${e.gi}-${e.ii}`,g.items[e.ii].warranty,'textarea',`equipment.${e.gi}.items.${e.ii}.warranty`,true)}`}<p class="panel-price-hint" ${A.priceNeedsReview(app.quote)?'':'hidden'}>Check total price when returning to the quotation. The existing total may still be valid.</p></div></div>`;}
function showEquipmentPanel(gi,ii=null,fromGroup=false){saveDraft();const old=app.editor;if(old?.ii===null&&ii!==null)app.panelListScroll=document.querySelector('.panel-body')?.scrollTop||0;if(!old)app.panelReturn={focus:document.activeElement?.id,scroll:window.scrollY};app.editor={gi,ii,fromGroup};document.querySelector('#equipment-panel')?.remove();const host=document.createElement('div');host.innerHTML=panelMarkup();document.body.append(host.firstElementChild);if(ii===null&&old&&old.ii!==null)document.querySelector('.panel-body').scrollTop=app.panelListScroll||0;$('app').inert=true;document.body.classList.add('panel-open');fieldEvents(app.quote);bindQuoteEquipment();if($('add-custom-item'))$('add-custom-item').onclick=()=>{const itemIndex=addQuoteCustomItem(gi);showEquipmentPanel(gi,itemIndex,true);$(`item-description-${gi}-${itemIndex}`)?.focus({preventScroll:true});};$('equipment-back').onclick=()=>{if(app.editor.ii!==null&&app.editor.fromGroup){const current=app.editor;showEquipmentPanel(current.gi);$(`spec-item-${current.gi}-${current.ii}`)?.focus({preventScroll:true});}else closeEquipmentPanel();};$('equipment-panel').onkeydown=e=>{if(e.key==='Escape'){$('equipment-back').click();e.preventDefault();}if(e.key==='Tab'){const nodes=Array.from($('equipment-panel').querySelectorAll('button,input,textarea')).filter(x=>!x.disabled),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}};$('equipment-back').focus({preventScroll:true});}
function addQuoteCustomItem(gi){const items=app.quote.equipment[gi].items;items.push({description:'',quantity:'',warranty:'',enabled:true});app.quote.referenceReviewed=false;saveDraft();updatePriceReminder();return items.length-1;}
function closeEquipmentPanel(){saveDraft();document.querySelector('#equipment-panel')?.remove();app.editor=null;$('app').inert=false;document.body.classList.remove('panel-open');quoteEquipmentAppearance();const target=$(app.panelReturn?.focus);target?.focus({preventScroll:true});if(window.scrollY!==app.panelReturn?.scroll)window.scrollTo(0,app.panelReturn?.scroll||0);}
function showAddScopeItem(){
 app.panelReturn={focus:document.activeElement?.id,scroll:window.scrollY};app.editor={adding:true};
 const host=document.createElement('div');host.innerHTML=`<div id="equipment-panel" class="equipment-panel" role="dialog" aria-modal="true" aria-labelledby="equipment-panel-title"><header class="panel-header">${button('equipment-back','← Back to quotation','secondary')}<h2 id="equipment-panel-title">Add equipment item</h2><p class="muted">For this quotation only. Defaults stay unchanged.</p></header><div class="panel-body"><form id="scope-add-form"><label class="field" for="new-item-category"><span>Category</span><select id="new-item-category">${app.quote.equipment.map((g,gi)=>`<option value="${gi}">${esc(g.name)}</option>`).join('')}<option value="new">+ New category</option></select></label><label class="field" id="new-category-field" for="new-category-name" hidden><span>New category name *</span><input id="new-category-name" type="text"></label><label class="field" for="new-item-description"><span>Item / specification *</span><textarea id="new-item-description" required rows="3"></textarea></label><label class="field" for="new-item-quantity"><span>Quantity</span><input id="new-item-quantity" type="text" placeholder="e.g. 3 pieces or 12 m"></label><label class="field" for="new-item-warranty"><span>Warranty</span><input id="new-item-warranty" type="text"></label><p id="scope-add-error" role="alert" class="scope-review-hint" hidden></p><button type="submit" class="primary">Add item</button></form></div></div>`;document.body.append(host.firstElementChild);$('app').inert=true;document.body.classList.add('panel-open');
 $('new-item-category').onchange=()=>{const isNew=$('new-item-category').value==='new';$('new-category-field').hidden=!isNew;$('new-category-name').required=isNew;};
 $('equipment-back').onclick=closeEquipmentPanel;
 $('equipment-panel').onkeydown=e=>{if(e.key==='Escape'){closeEquipmentPanel();e.preventDefault();}if(e.key==='Tab'){const nodes=Array.from($('equipment-panel').querySelectorAll('button,input,textarea,select')).filter(x=>!x.disabled&&!x.closest('[hidden]')),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}};
 $('scope-add-form').onsubmit=e=>{e.preventDefault();const category=$('new-item-category').value,name=$('new-category-name').value.trim(),description=$('new-item-description').value.trim();if(!description||(category==='new'&&!name)){const error=$('scope-add-error');error.hidden=false;error.textContent=!description?'Enter the item / specification.':'Enter a new category name.';return;}const item={description,quantity:$('new-item-quantity').value.trim(),warranty:$('new-item-warranty').value.trim(),enabled:true};if(category==='new')app.quote.equipment.push({name,enabled:true,battery:false,items:[item]});else {const gi=Number(category);if(!app.quote.equipment[gi])return;const group=app.quote.equipment[gi];if(!group.enabled){group.items.forEach(existing=>existing.enabled=false);group.enabled=true;}group.items.push(item);}app.quote.referenceReviewed=false;closeEquipmentPanel();render();$('add-scope-item')?.focus({preventScroll:true});if(window.scrollY!==app.panelReturn?.scroll)window.scrollTo(0,app.panelReturn?.scroll||0);};
 $('new-item-description').focus({preventScroll:true});
}
function bindQuoteEquipment(){if($('add-scope-item'))$('add-scope-item').onclick=showAddScopeItem;app.quote.equipment.forEach((g,gi)=>{const edit=$(`edit-group-${gi}`);if(edit)edit.onclick=()=>showEquipmentPanel(gi);g.items.forEach((_,ii)=>{const spec=$(`spec-item-${gi}-${ii}`);if(spec)spec.onclick=()=>showEquipmentPanel(gi,ii,!!app.editor);});});}
function quantityField(gi,ii,item){const id=ii===0?`row-quantity-${gi}`:`item-quantity-${gi}-${ii}`;return `<label class="scope-quantity" for="${id}"><span>Quantity</span><textarea id="${id}" rows="1" data-autogrow data-path="equipment.${gi}.items.${ii}.quantity" aria-describedby="quantity-hint-${gi}-${ii}" ${app.quote.equipment[gi].enabled&&item.enabled?'':'disabled'}>${esc(item.quantity)}</textarea><span class="quantity-hint" id="quantity-hint-${gi}-${ii}" ${ambiguousQuantity(item.quantity)?'':'hidden'}>Quantity needs review</span></label>`;}
function inclusionField(gi,ii,item){return `<label class="scope-include" title="Include this item in quotation"><input type="checkbox" role="switch" aria-label="Include ${esc(item.description||'custom item')} in quotation" data-path="equipment.${gi}.items.${ii}.enabled" ${app.quote.equipment[gi].enabled&&item.enabled?'checked':''}><span class="switch-track" aria-hidden="true"></span></label>`;}
function scopeStatus(g){if(g.items.length===1)return `Quantity: ${g.items[0].quantity||'Not set'} · ${g.enabled&&g.items[0].enabled?'Included':'Not included'}`;return `${g.enabled?g.items.filter(i=>i.enabled).length:0} of ${g.items.length} included`;}
function quoteEquipment(q){A.ensureEquipmentState(q);return `<p class="table-help">Standard equipment is ready. Change only what this quotation needs.</p><div class="scope-overview">${q.equipment.map((g,gi)=>`<article class="scope-group" data-group="${gi}"><div class="scope-heading"><h3>${esc(g.name)}</h3><span class="changed-badge" ${A.equipmentChanged(q,gi)?'':'hidden'}>Changed for this quotation</span>${`<button type="button" id="edit-group-${gi}" class="scope-edit" aria-label="Edit equipment: ${esc(g.name)}"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m16 3 5 5-12 12-6 1 1-6Z"/><path d="m14 5 5 5"/></svg><span>Edit</span></button>`}</div><p class="scope-summary">${esc(g.items.map(i=>i.description).join(' · '))}</p><p class="scope-count">${esc(scopeStatus(g))}</p>${g.items.length===1?`<p class="scope-review-hint" ${ambiguousQuantity(g.items[0].quantity)?'':'hidden'}>Quantity needs review</p>`:''}</article>`).join('')}</div>`;}
function quoteEquipmentAppearance(){const q=app.quote;document.querySelectorAll('.scope-group').forEach(el=>{const gi=Number(el.dataset.group),g=q.equipment[gi];el.querySelector('.changed-badge').hidden=!A.equipmentChanged(q,gi);const excluded=el.querySelector('.scope-excluded');if(excluded)excluded.hidden=g.enabled&&g.items[0].enabled;const summary=el.querySelector('.scope-summary');summary.textContent=g.items.map(i=>i.description).join(' · ');const count=el.querySelector('.scope-count');if(count)count.textContent=scopeStatus(g);const hint=el.querySelector('.scope-review-hint');if(hint)hint.hidden=!ambiguousQuantity(g.items[0].quantity);});if(app.editor){const g=q.equipment[app.editor.gi];$('equipment-panel').querySelectorAll('.scope-editor-item').forEach(el=>{const item=g.items[Number(el.dataset.item)];const active=g.enabled&&item.enabled;el.classList.toggle('is-excluded',!active);el.querySelectorAll('textarea,button.item-details-edit').forEach(control=>control.disabled=!active);});}document.querySelectorAll('.quantity-hint').forEach(h=>{const parts=h.id.split('-'),gi=Number(parts[2]),ii=Number(parts[3]);h.hidden=!ambiguousQuantity(q.equipment[gi].items[ii].quantity);});}
function categorySummary(g){const included=g.enabled?g.items.filter(i=>i.enabled).length:0;return g.items.length===1?`${included?'':'Excluded · '}${g.items[0].description||'Enter specification'}`:`${included} of ${g.items.length} included · View individual quantities`;}
function equipment(q){
 if(q===app.quote)return quoteEquipment(q);
 q.equipment=A.normalizeEquipment(q.equipment);const count=A.equipmentRows(q.equipment).length;
 const cell=(g,i,key,value)=>{const label={description:'Item / specification',quantity:'Quantity',warranty:'Warranty'}[key];const id=key==='description'?(i===0?`row-description-${g}`:`item-description-${g}-${i}`):i===0?`row-${key}-${g}`:`item-${key}-${g}-${i}`;return `<textarea id="${id}" rows="1" data-autogrow aria-label="${label}, group ${g+1}, item ${i+1}" data-path="equipment.${g}.items.${i}.${key}" ${key==='quantity'?`aria-describedby="quantity-hint-${g}-${i}"`:""} placeholder="${key==='quantity'?'e.g. 3 or 10 m':label}">${esc(value)}</textarea>`;};
 return `<div class="equipment-toolbar"><p class="table-help" id="equipment-table-help"><span class="desktop-help">Edit the cells. Uncheck items you do not need.</span><span class="mobile-help">Open a category to change its items or details.</span></p><div class="equipment-toolbar-actions"><span id="equipment-count" role="status" aria-live="polite">${count} items</span><button type="button" id="manage-equipment" class="quiet" aria-expanded="${!!app.manageEquipment}">${app.manageEquipment?'Done':'Manage equipment'}</button></div></div><div class="equipment-scroll ${app.manageEquipment?'is-managing':''}" id="equipment-scroll" role="region" aria-label="Editable equipment table" aria-describedby="equipment-table-help" tabindex="0"><table class="equipment-table"><caption class="sr-only">Editable equipment, individual item quantities and warranties</caption><colgroup><col class="col-group"><col class="col-item"><col class="col-qty"><col class="col-warranty"><col class="col-actions"></colgroup><thead><tr><th scope="col">Particulars</th><th scope="col">Items / specification</th><th scope="col">Qty</th><th scope="col">Warranty</th><th scope="col" class="equipment-management">Actions</th></tr></thead>${q.equipment.map((g,gi)=>{
 const single=g.items.length===1;
 return `<tbody class="equipment-group ${single?'is-single':'is-multi'} ${!g.enabled?'is-excluded':''}" data-group="${gi}"><tr class="category-overview"><td colspan="5"><button type="button" class="category-toggle" id="toggle-category-${gi}" aria-expanded="false" aria-controls="category-fields-${gi} ${g.items.map((_,ii)=>`equipment-item-${gi}-${ii}`).join(' ')}"><span class="category-name">${esc(g.name||'Unnamed category')}</span><span class="category-summary">${esc(categorySummary(g))}</span><span class="category-chevron" aria-hidden="true">⌄</span></button></td></tr>
 <tr class="category-fields equipment-management" id="category-fields-${gi}"><td colspan="5"><label class="category-name-label" for="row-name-${gi}">Category name</label><textarea class="equipment-management" id="row-name-${gi}" rows="1" data-autogrow aria-label="Category name, group ${gi+1}" data-path="equipment.${gi}.name">${esc(g.name)}</textarea><label class="table-check equipment-management"><input type="checkbox" data-path="equipment.${gi}.enabled" ${g.enabled?'checked':''}><span>Include category</span></label></td></tr>
 ${g.items.map((item,ii)=>`<tr id="equipment-item-${gi}-${ii}" class="equipment-item ${!item.enabled?'is-excluded':''}" data-item="${ii}">${ii===0?`<td rowspan="${g.items.length}" class="group-cell" data-label="Particulars"><span class="group-name-text">${esc(g.name)}</span></td>`:''}<td class="item-specification" data-label="Item / specification"><div class="specification-controls"><label class="table-check item-include"><input type="checkbox" aria-label="Include item ${ii+1} in group ${gi+1}" data-path="equipment.${gi}.items.${ii}.enabled" ${item.enabled?'checked':''}></label><span class="item-description-summary">${esc(item.description||'Enter specification')}</span>${cell(gi,ii,'description',item.description)}</div></td><td class="item-quantity" data-label="Qty"><div class="quantity-control">${cell(gi,ii,'quantity',item.quantity)}<span class="quantity-hint" id="quantity-hint-${gi}-${ii}" ${ambiguousQuantity(item.quantity)?'':'hidden'}>Confirm quantity</span></div>${single?'':`<button type="button" class="mobile-item-edit quiet" id="edit-item-${gi}-${ii}" aria-expanded="false" aria-label="Details for item ${ii+1} in ${esc(g.name)}" aria-controls="${ii===0?`row-description-${gi}`:`item-description-${gi}-${ii}`} ${ii===0?`row-warranty-${gi}`:`item-warranty-${gi}-${ii}`}">Details</button>`}</td><td class="item-warranty" data-label="Warranty"><span class="warranty-summary">${esc(item.warranty||'Not set')}</span>${cell(gi,ii,'warranty',item.warranty)}</td><td class="item-actions equipment-management"><div class="item-action-controls"><button type="button" id="remove-item-${gi}-${ii}" class="quiet" aria-label="Remove item ${ii+1} from group ${gi+1}">×</button></div></td></tr>`).join('')}<tr class="group-tools equipment-management"><td colspan="5"><div class="group-tool-controls">${button(`add-item-${gi}`,'+ Add item','quiet')}${button(`remove-row-${gi}`,'Remove category','quiet')}</div></td></tr></tbody>`;
 }).join('')}</table></div><div class="equipment-add-group ${app.manageEquipment?'':'is-hidden'}">${button('add-row','+ Add equipment category','secondary')}</div>`;
}
function equipmentAppearance(obj){if(obj===app.quote){quoteEquipmentAppearance();return;}document.querySelectorAll('.equipment-group').forEach(body=>{const group=obj.equipment[Number(body.dataset.group)];body.classList.toggle('is-excluded',!group.enabled);body.querySelector('.category-name').textContent=group.name||'Unnamed category';body.querySelector('.group-name-text').textContent=group.name;body.querySelector('.category-summary').textContent=categorySummary(group);body.querySelectorAll('[data-item]').forEach(row=>{const item=group.items[Number(row.dataset.item)];row.classList.toggle('is-excluded',!item.enabled);row.querySelector('.quantity-hint').hidden=!ambiguousQuantity(item.quantity);row.querySelector('.item-description-summary').textContent=item.description||'Enter specification';row.querySelector('.warranty-summary').textContent=item.warranty||'Not set';});});if($('equipment-count'))$('equipment-count').textContent=`${A.equipmentRows(obj.equipment).length} items`;}
function bindEquipment(obj){
 $('manage-equipment').onclick=()=>{app.manageEquipment=!app.manageEquipment;render();};
 // Open categories are DOM-only UI state, never quotation/default/backup fields.
 const change=(fn,message,focusId)=>{
  if(message&&!confirm(message))return;
  const left=$('equipment-scroll')?.scrollLeft||0,before=obj.equipment.slice(),active=document.activeElement;
  const activeGroup=active?.closest('.equipment-group'),activeIndex=Number(activeGroup?.dataset.group||0);
  const opened=Array.from(document.querySelectorAll('.equipment-group.is-open'),body=>obj.equipment[Number(body.dataset.group)]);
  fn();
  const openIndices=obj.equipment.map((g,i)=>opened.includes(g)||!before.includes(g)?i:-1).filter(i=>i>=0);
  const targetIndex=obj.equipment.indexOf(before[activeIndex]);
  if(obj===app.quote){app.quote.referenceReviewed=false;saveDraft();}
  render();
  openIndices.forEach(i=>{const toggle=$(`toggle-category-${i}`);toggle.closest('.equipment-group').classList.add('is-open');toggle.setAttribute('aria-expanded','true');});
  if($('equipment-scroll'))$('equipment-scroll').scrollLeft=left;
  const fallback=window.innerWidth<=700?`toggle-category-${Math.max(0,targetIndex)}`:`add-item-${Math.max(0,targetIndex)}`;
  const target=$(focusId||'')||$(fallback)||$('add-row');
  if(focusId?.startsWith('item-description-')){const row=target.closest('.equipment-item'),edit=row?.querySelector('.mobile-item-edit');if(edit&&!row.classList.contains('is-editing'))edit.click();}
  target?.focus({preventScroll:true});document.querySelectorAll('[data-autogrow]').forEach(fitTextarea);
 };
 $('add-row').onclick=()=>change(()=>obj.equipment.push({name:'',description:'',quantity:'As Required',warranty:'Standard',enabled:true,battery:false,items:[{description:'',quantity:'As Required',warranty:'Standard',enabled:true}]}),null,`row-name-${obj.equipment.length}`);
 obj.equipment.forEach((g,gi)=>{
  const toggle=$(`toggle-category-${gi}`);
  toggle.onclick=()=>{const body=toggle.closest('.equipment-group'),open=body.classList.toggle('is-open');toggle.setAttribute('aria-expanded',String(open));body.querySelectorAll('[data-autogrow]').forEach(fitTextarea);};
  $(`add-item-${gi}`).onclick=()=>change(()=>g.items.push({description:'',quantity:'As Required',warranty:g.warranty||'Standard',enabled:true}),null,`item-description-${gi}-${g.items.length}`);
  $(`remove-row-${gi}`).onclick=()=>change(()=>obj.equipment.splice(gi,1),'Remove this entire equipment group and its items?');
  g.items.forEach((item,ii)=>{
   const edit=$(`edit-item-${gi}-${ii}`);
   if(edit)edit.onclick=()=>{const row=edit.closest('.equipment-item'),open=row.classList.toggle('is-editing');edit.textContent=open?'Done':'Details';edit.setAttribute('aria-expanded',String(open));edit.setAttribute('aria-label',`${open?'Done editing':'Details for'} item ${ii+1} in ${g.name}`);row.querySelectorAll('[data-autogrow]').forEach(fitTextarea);};
   $(`remove-item-${gi}-${ii}`).onclick=()=>change(()=>{g.items.splice(ii,1);if(!g.items.length)obj.equipment.splice(gi,1);},g.items.length===1?'Remove the last item and this equipment group?':'Remove this individual item?');
  });
 });
}
function equipmentReview(q){const rows=A.equipmentRows(q.equipment);return `<div class="review-equipment equipment-scroll"><table class="review-item-table"><caption class="sr-only">Included equipment and individual quantities</caption><thead><tr><th scope="col">Particulars</th><th scope="col">Items / specification</th><th scope="col">Qty</th><th scope="col">Warranty</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i===0||rows[i-1].groupIndex!==r.groupIndex?esc(r.name):''}</td><td>${esc(r.description)}</td><td>${esc(r.quantity)}</td><td>${esc(r.warranty)}</td></tr>`).join('')}</tbody></table></div>`;}
function system(){const q=app.quote;return `<section class="card investment-card"><h2>System & investment</h2><div class="fields investment-fields">${input('System capacity (kW) *','capacity',q.capacity,'number')}${input('Total cost incl. GST (Rs.) *','cost',q.cost,'number')}${input('Estimated subsidy (Rs.)','subsidy',q.subsidy,'number')}</div><div class="effective-cost"><span>Estimated effective cost</span><strong id="net-value">${P.money(A.amounts(q).net)}</strong></div><h3 class="payment-heading">Payment split (%)</h3><div class="fields three payment-split">${['Advance','Delivery','Completion'].map((s,i)=>input(s,`payment-${i}`,q.payments[i],'number',`payments.${i}`)).join('')}</div></section><details id="reference-guidance" class="reference-guidance"><summary>Reference values — check before sharing</summary><p>Capacity, total cost and subsidy start from editable reference values. Check them for this lead. Enter the full GST-inclusive vendor price and estimated subsidy separately. Subsidy does not reduce the amount due to the vendor; payment percentages must add up to 100%.</p></details>${priceReminder()}<section class="card"><div class="scope-section-heading"><h2>Equipment & scope</h2>${button('add-scope-item','+ Add item','quiet')}</div>${equipment(q)}</section><section class="card"><h2>Details & conditions</h2>${detailsFields(q)}</section>`;}
function review(){const q=app.quote;return `<section class="card" id="review"><h2>Customer PDF preview</h2><p class="muted">Content preview only. Select View PDF to check the final page layout.</p><div class="review-brand"><p class="eyebrow">${esc(q.company.tagline)}</p><h2>${esc(q.company.name)}</h2><p>${esc(q.company.address)}<br>${esc(q.company.phone)} · ${esc(q.company.email)}<br>GSTIN ${esc(q.company.gstin)}</p></div><div class="review-meta"><strong>QUOTATION ${esc(q.number)}</strong><span>${esc(q.date)} · valid ${esc(q.validity)} days</span></div><h3>Prepared for</h3><p class="preserve">${esc(q.customer.name)}\n${esc(q.customer.address)}\n${esc(q.customer.phone)} ${esc(q.customer.email)}\nConsumer: ${esc(q.customer.consumer||'Not provided')}</p><h3>Hybrid rooftop solar · ${esc(q.capacity)} kW</h3>${equipmentReview(q)}<div class="price-strip"><div><small>TOTAL INCL. GST / VENDOR DUE</small><strong>${P.money(q.cost)}</strong></div><div><small>ESTIMATED SUBSIDY</small><strong>${P.money(q.subsidy)}</strong></div><div><small>INDICATIVE EFFECTIVE COST</small><strong>${P.money(A.amounts(q).net)}</strong></div></div><p class="notice">${esc(P.disclaimer)}</p><h3>System details</h3><p>${esc(q.generation)}<br>${esc(q.life)} · ${esc(q.maintenance)}</p><h3>Payment schedule</h3><p>Advance ${esc(q.payments[0])}% · Delivery ${esc(q.payments[1])}% · Completion ${esc(q.payments[2])}% of vendor total.</p><h3>Terms & conditions</h3><p class="preserve">${esc(q.terms)}</p><h3>Required documents</h3><p>${esc(q.documents)}</p><h3>Bank details</h3>${P.isTestBank(q.company)?'<p class="notice"><b>TEST ONLY — NOT FOR PAYMENT.</b> Fictional bank details enable PDF download testing.</p>':''}<p>Account name: ${esc(q.company.bankName)}<br>Account: ${esc(q.company.account)}<br>IFSC: ${esc(q.company.ifsc)}</p><p class="bank-warning">${P.bankErrors(q.company).map(esc).join('<br>')}</p><div class="signatures"><p>Authorized signature<br>______________________</p><p>Accepted by customer<br>______________________</p></div></section><label class="check review-check"><input id="referenceReviewed" data-path="referenceReviewed" type="checkbox" ${q.referenceReviewed?'checked':''}><span>I have checked the customer details, item quantities, price, estimated subsidy, payment terms and bank details.</span></label>`;}
function bindQuote(){fieldEvents(app.quote);if($('next'))$('next').onclick=()=>{if(app.step===0&&(!app.quote.customer.name.trim()||!app.quote.customer.address.trim()))return notify('Enter customer name and address before continuing.',true);clearNotification();app.step++;render();if(window.scrollY)window.scrollTo(0,0);};if($('back'))$('back').onclick=()=>{clearNotification();app.step--;render();if(window.scrollY)window.scrollTo(0,0);};if(app.step===1){bindQuoteEquipment();$('price-checked').onclick=()=>{A.acknowledgePrice(app.quote);saveDraft();updatePriceReminder();};}if($('save'))$('save').onclick=()=>guard(()=>{store.save(app.quote);render();notify(storageOK?'Quotation saved on this device. Back up regularly.':'Quotation retained in session only. Download a backup.',!storageOK);});if($('pdf'))$('pdf').onclick=()=>guard(()=>showQuotationPDF(app.quote,$('pdf'),'current'));}
function history(){const savedCurrent=store.state.quotes.find(q=>q.id&&q.id===app.quote.id);const workingChanged=savedCurrent&&JSON.stringify(app.quote)!==JSON.stringify(savedCurrent);return `<section class="page-heading workspace-heading"><div><h1>Quotations</h1><p>Create a quotation or continue where you left off.</p></div>${button('new','+ New quotation','primary')}</section><section class="card draft-card"><div><div class="working-copy-heading"><h2>${savedCurrent?'Current working copy':'Current draft'}</h2><span class="working-copy-status ${workingChanged?'has-unsaved-changes':''}">${savedCurrent?(workingChanged?'Unsaved changes':'Editing saved quotation'):'Draft'}</span></div><p>${esc(app.quote.customer.name||'No customer entered yet')} · Quotation ${esc(app.quote.number)}</p><p class="working-copy-note">${savedCurrent?'View PDF below shows the last saved version. Save quotation to update it.':'Not saved as a quotation yet. Resume to finish and save it.'}</p></div>${button('nav-quote',savedCurrent?'Resume editing →':'Resume draft →','secondary')}</section><section class="history-list" aria-labelledby="saved-quotations-title"><h2 id="saved-quotations-title">Saved quotations</h2>${store.state.quotes.length?store.state.quotes.slice().reverse().map((q,i)=>`<article class="card history-card"><div class="quotation-card-meta"><p>Quotation ${esc(q.number)}</p><span class="quotation-status">Saved</span></div><h3 class="quotation-customer">${esc(q.customer.name)}</h3><p class="quotation-purpose">${esc(q.capacity)} kW rooftop solar</p><div class="quotation-card-details"><span>${esc(q.date)}</span><strong>${P.money(q.cost)} <small>incl. GST</small></strong></div><div class="history-actions">${button(`view-pdf-${i}`,'View PDF','primary')}${button(`open-${i}`,'Edit','secondary')}</div><details class="quotation-more"><summary>More options</summary><div>${button(`duplicate-${i}`,'New customer','quiet')}${button(`delete-${i}`,'Delete quotation','danger')}</div></details></article>`).join(''):'<div class="empty card"><h3>No saved quotations yet</h3><p>Finish the draft and select Save quotation to add it here.</p></div>'}</section><details class="backup-tools"><summary>Backup &amp; restore</summary><p class="muted">${storageOK?'Saved only in this browser on this device.':'Storage is unavailable. Changes are session-only; export a backup before closing.'} No cloud sync. Back up regularly.</p>${button('backup','Export backup ↓','secondary')}<section class="card"><h2>Restore a backup</h2><p class="muted">A valid JSON backup replaces all local quotations, settings and the draft after confirmation. Keep a current backup first. Backup files contain personal data: store them securely.</p><label class="file-label">Choose JSON backup<input id="restore" type="file" accept=".json,application/json"></label></section></details>`;}
function downloadJSON(){const b=new Blob([store.backup()],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=`Nav-Bharat-backup-${A.localDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function bindHistory(){$('backup').onclick=()=>guard(downloadJSON);$('restore').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>20000000)throw Error('Backup exceeds 20 MB limit.');const json=await f.text();store.restore(json,false);if(confirm('Replace ALL local quotations, settings and draft with this backup? This cannot be undone.')){store.restore(json,true);app.quote=store.state.draft||store.create();render();notify('Backup restored.');}}catch(err){notify(err.message,true);}e.target.value='';};store.state.quotes.slice().reverse().forEach((q,i)=>{$(`view-pdf-${i}`).onclick=()=>guard(()=>showQuotationPDF(q,$(`view-pdf-${i}`)));$(`open-${i}`).onclick=()=>{app.quote=store.open(q.id);saveDraft();app.step=0;nav('quote');};$(`duplicate-${i}`).onclick=()=>{app.quote=store.duplicate(q);app.step=0;nav('quote');};$(`delete-${i}`).onclick=()=>guard(()=>{if(store.remove(q.id,confirm(`Delete quotation ${q.number}? This cannot be undone.`))){if(app.quote.id===q.id){app.quote=store.create();saveDraft();}render();notify('Quotation deleted.');}});});}
function showQuotationPDF(q,trigger,source='saved'){
  if(app.pdfPreview)closeQuotationPDF();
  const doc=P.buildPDF(A.clone(q));
  clearNotification();
  const url=URL.createObjectURL(doc.output('blob'));
  const panel=document.createElement('section');
  panel.id='saved-pdf-preview';panel.className='saved-pdf-preview';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','saved-pdf-title');
  const filename=`Nav-Bharat-${q.number.replace(/[^A-Za-z0-9-]/g,'-')}.pdf`;
  panel.innerHTML=`<header class="saved-pdf-toolbar"><button id="saved-pdf-close" class="quiet">${source==='current'?'← Back to review':'← Quotations'}</button><div class="saved-pdf-actions"><a id="saved-pdf-open" class="secondary button" href="${esc(url)}" target="_blank" rel="noopener noreferrer">Open PDF</a><a id="saved-pdf-download" class="primary button" href="${esc(url)}" download="${esc(filename)}">Download PDF</a></div></header><div class="saved-pdf-heading"><h2 id="saved-pdf-title">Quotation ${esc(q.number)}</h2><p>${esc(q.customer.name)} · ${source==='current'?'Current quotation':'Last saved version'}</p>${source==='current'?'<p>Preview only — use Save quotation to update saved records.</p>':''}${P.isTestBank(q.company)?'<p class="saved-pdf-test">TEST ONLY — NOT FOR PAYMENT</p>':''}<p class="saved-pdf-fallback">If the preview is blank, select Open PDF.</p></div><iframe title="${esc(`PDF preview: Quotation ${q.number}`)}" src="${esc(url)}"></iframe>`;
  const keyHandler=e=>{if(e.key==='Escape'){e.preventDefault();closeQuotationPDF();}else if(e.key==='Tab'){const nodes=panel.querySelectorAll('button,a[href],iframe'),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};
  app.pdfPreview={url,panel,trigger,keyHandler,source};$('app').inert=true;document.body.classList.add('pdf-preview-open');document.body.append(panel);document.addEventListener('keydown',keyHandler);$('saved-pdf-close').onclick=closeQuotationPDF;$('saved-pdf-close').focus();
}
function closeQuotationPDF(){const preview=app.pdfPreview;if(!preview)return;delete app.pdfPreview;document.removeEventListener('keydown',preview.keyHandler);preview.panel.remove();URL.revokeObjectURL(preview.url);$('app').inert=false;document.body.classList.remove('pdf-preview-open');if(preview.trigger.isConnected)preview.trigger.focus({preventScroll:true});}
function settings(){const s=app.settings;const labels={name:'Company name',tagline:'Company tagline',phone:'Mobile / WhatsApp',gstin:'GSTIN',address:'Office address',email:'Email',bankName:'Bank account name',account:'Bank account number',ifsc:'IFSC (as entered)'};return `<section class="page-heading"><div><p class="eyebrow">MAKE IT YOURS</p><h1>Configure your workspace.</h1><p>Defaults apply to new quotations. Existing quotes retain their own snapshots.</p></div></section><section class="card"><h2>Company & bank details</h2><div class="fields">${Object.entries(labels).map(([k,v])=>input(v,`company-${k}`,s.company[k],k==='address'?'textarea':'text',`company.${k}`,k==='address')).join('')}</div><aside class="notice"><b>Set up the bank details</b><p>Enter the account name, account number and IFSC as supplied. The confirmation checkbox is optional and does not block PDF viewing or download. Save defaults for future quotations, or use Apply company &amp; bank to update the current quotation.</p></aside><label class="check"><input id="bankVerified" data-path="company.bankVerified" type="checkbox" ${s.company.bankVerified?'checked':''}><span>I have independently confirmed these bank details (optional).</span></label><div class="settings-company-action">${button('apply-company','Apply company & bank to current quote','secondary')}<p class="muted">Updates company details only. Your current customer, equipment and pricing are preserved.</p></div></section><section class="card"><h2>Default quotation values</h2><p class="muted">Set the starting values for new quotations. Select Save defaults to keep them. Existing quotations stay unchanged unless you select Apply defaults to current quote.</p><div class="fields">${input('Default capacity (kW)','capacity',s.capacity,'number')}${input('Default cost incl. GST (Rs.)','cost',s.cost,'number')}${input('Estimated subsidy (Rs.)','subsidy',s.subsidy,'number')}${input('Validity (days)','validity',s.validity,'number')}${s.payments.map((v,i)=>input(['Advance (%)','Delivery (%)','Completion (%)'][i],`payment-${i}`,v,'number',`payments.${i}`)).join('')}</div></section><section class="card"><h2>Default equipment</h2>${equipment(s)}</section><section class="card"><h2>Default details & conditions</h2>${detailsFields(s)}</section><div class="wizard-actions">${button('apply-settings','Apply defaults to current quote','secondary')}${button('save-settings','Save defaults','primary')}</div>`;}
function bindSettings(){fieldEvents(app.settings);$('apply-company').onclick=()=>guard(()=>{const errors=P.bankErrors(app.settings.company);if(errors.length)throw Error(errors.join('\n'));if(confirm('Update company and bank details on the current quote? Price and equipment will not change.')){app.quote.company=A.clone(app.settings.company);app.quote.referenceReviewed=false;saveDraft();notify('Current quote company and bank updated. Save defaults separately for future quotes.');}});bindEquipment(app.settings);$('save-settings').onclick=()=>guard(()=>{const test=A.newQuote(app.settings,1);test.customer.name='Validation';test.customer.address='Validation';test.referenceReviewed=true;const errors=A.validate(test);if(app.settings.company.bankVerified)errors.push(...P.bankErrors(app.settings.company));if(errors.length)throw Error(errors.join('\n'));store.state.settings=A.clone(app.settings);store.persist();notify('Defaults saved. They apply to new quotations.');});$('apply-settings').onclick=()=>guard(()=>{if(confirm('Replace company, equipment, pricing and terms on the current quote with these defaults? Customer and quotation identity will remain.')){const q=app.quote;app.quote={...A.clone(app.settings),id:q.id,number:q.number,date:q.date,customer:A.clone(q.customer),equipmentState:A.clone(A.ensureEquipmentState(q)),referenceReviewed:false};saveDraft();app.step=1;nav('quote');}});}
if(!store.state.draft)saveDraft();render();if(!storageOK)notify('Local storage is unavailable or unreadable. Existing stored data was not overwritten. Export backups to retain this session.',true);
})();
