(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.QuoteCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const referenceParts={
 'C Channel GI (Tata, Jsw), Purlin GI (Tata, Jsw)':['C Channel GI (Tata, Jsw)','Purlin GI (Tata, Jsw)'],
 'Base Plate, Fastnut, Nut Bolt, Mid Clamp, End Clamp, U Bolt, J Bolt':['Base Plate','Fastnut','Nut Bolt','Mid Clamp','End Clamp','U Bolt','J Bolt'],
 'PVC Pipe, Elbow, Tee, Tape, Lugs 4 sq mm':['PVC Pipe','Elbow PVC','PVC Tee','PVC Tape','Lugs 4 sq mm'],
 'ACDB H+S DCDB H+H, Cable Tray, Cable Tie, 4 sq mm DC Wire, 6 sq mm AC Wire, Red 2.5 sq mm AC Earthing Wire, Wire Clip (Anchor Wire)':['ACDB H+S','DCDB H+H','Cable Tray','Cable Tie','4 sq mm DC Wire','6 sq mm AC Wire','Red 2.5 sq mm AC Earthing Wire','Wire Clip (Anchor Wire)'],
 'Ittorent Earthing Rod 2m Copper Bonded, LA 2m, Chemical Bag 15kg, Earthing Pit Cover':['Ittorent Earthing Rod 2m','Copper Bonded LA 2m','Chemical Bag 15kg','Earthing Pit Cover']
};
function legacyItems(g){const parts=referenceParts[g.description]||[g.description];const vector=g.quantity.split('/');const quantities=parts.length>1&&vector.length===parts.length?vector:parts.map((_,i)=>i===0||g.quantity==='As Required'?g.quantity:'');return parts.map((description,i)=>({description,quantity:quantities[i],warranty:g.warranty,enabled:true}));}
function normalizeEquipment(list){return list.map(g=>{const r=clone(g);if(!r||typeof r!=='object'||Array.isArray(r))return r;if(r.items===undefined&&typeof r.description==='string'&&typeof r.quantity==='string'&&typeof r.warranty==='string')r.items=legacyItems(r);return r;});}
function equipmentRows(list){const rows=[];for(const [groupIndex,g] of normalizeEquipment(list).entries()){if(!g.enabled)continue;for(const [itemIndex,item] of g.items.entries()){if(item.enabled)rows.push({groupIndex,itemIndex,name:g.name,description:item.description,quantity:item.quantity,warranty:item.warranty});}}return rows;}

function defaults(){return {company:{name:'NAV BHARAT ENTERPRISES',tagline:'Government Approved Vendor',phone:'+91-9699445941',gstin:'10BXFPA4890P1ZC',address:'Shahnaz Manjil, Dharampur Samastipur, Bihar 848101',email:'khursheedalam36@gmail.com',bankName:'Nav Bharat Enterprises',account:'43556255447',ifsc:'SBIN000174',bankVerified:false},capacity:5,cost:485000,subsidy:98000,payments:[80,15,5],validity:15,generation:'7,300–9,125 kWh yearly (estimate for reference system; site conditions affect output)',life:'25+ years',maintenance:'5 years free maintenance',equipment:[
['Solar PV Module','Waaree Topcon N type Bi-facial DCR Panel','9/10 Panel','25 to 30 Years'],['Hybrid Inverter','Deye, UTL (5 KW Inverter)','1','5 to 8 Years'],['Battery','UTL Lithium-ion','As Required','5 Years'],['Mounting Structure','C Channel GI (Tata, Jsw), Purlin GI (Tata, Jsw)','As Required','Standard'],['Structure Accessories','Base Plate, Fastnut, Nut Bolt, Mid Clamp, End Clamp, U Bolt, J Bolt','As Required','Standard'],['BOS Accessories','PVC Pipe, Elbow, Tee, Tape, Lugs 4 sq mm','As Required','Standard'],['BOS & Wires','ACDB H+S DCDB H+H, Cable Tray, Cable Tie, 4 sq mm DC Wire, 6 sq mm AC Wire, Red 2.5 sq mm AC Earthing Wire, Wire Clip (Anchor Wire)','As Required','Standard'],['Earthing Kit','Ittorent Earthing Rod 2m Copper Bonded, LA 2m, Chemical Bag 15kg, Earthing Pit Cover','3/1/1/3','Standard']].map((r,i)=>{const g={name:r[0],description:r[1],quantity:r[2],warranty:r[3],enabled:true,battery:i===2};g.items=legacyItems(g);return g;}),terms:'Delivery within 10 days of confirmation. Installation within 7 days of delivery.\nApplicant name, address and consumer number must match supporting documents.\nEstimated subsidy is subject to eligibility, inspection and approval under applicable policy. It is paid directly to the customer, not deducted from the amount payable to the vendor. No approval or payment timeline is promised.\nIncludes material, transport, labour, installation and commissioning. Extra work is charged separately.\nWarranty and subsidy are subject to applicable policy and manufacturer terms.\nConcrete, sand, cement and aggregate for up to 12-inch grouting are provided by the customer; 3–4-inch holes for each base plate.\nActual rate may vary after site visit. Financing, if requested, is subject to lender assessment and terms.',documents:'Aadhaar; PAN; photograph; latest electricity bill; cancelled cheque or passbook'};}
function priceSignature(q){return JSON.stringify({capacity:q.capacity,equipment:normalizeEquipment(q.equipment).map(g=>({name:g.name,enabled:g.enabled,items:g.items.map(i=>({description:i.description,quantity:i.quantity,enabled:i.enabled}))}))});}
function ensureEquipmentState(q){if(!q.equipmentState)q.equipmentState={baseline:normalizeEquipment(q.equipment)};if(q.equipmentState.priceChecked===undefined)q.equipmentState.priceChecked=priceSignature(q);return q.equipmentState;}
function priceNeedsReview(q){return ensureEquipmentState(q).priceChecked!==priceSignature(q);}
function acknowledgePrice(q){ensureEquipmentState(q).priceChecked=priceSignature(q);}
function equipmentChanged(q,index){const state=ensureEquipmentState(q);return JSON.stringify(q.equipment[index])!==JSON.stringify(state.baseline[index]);}
function newQuote(settings,sequence){const q={...clone(settings),id:'',number:`${sequence}/${new Date().getFullYear()}`,date:localDate(),customer:{name:'',address:'',phone:'',email:'',consumer:''},referenceReviewed:false};ensureEquipmentState(q);return q;}
const numeric=x=>x!==''&&x!==null&&Number.isFinite(Number(x));
function validate(q){const e=[];if(!q.customer||!String(q.customer.name||'').trim())e.push('Enter customer name.');if(!q.customer||!String(q.customer.address||'').trim())e.push('Enter customer address.');if(!/^\d{4}-\d{2}-\d{2}$/.test(q.date)||!Number.isFinite(Date.parse(q.date))||new Date(q.date+'T12:00:00').toISOString().slice(0,10)!==q.date)e.push('Enter a valid quotation date.');if(!String(q.number||'').trim())e.push('Enter quotation number.');if(!numeric(q.capacity)||Number(q.capacity)<=0)e.push('Enter positive system capacity.');if(!numeric(q.cost)||Number(q.cost)<=0)e.push('Enter positive total cost.');if(!numeric(q.subsidy)||Number(q.subsidy)<0||Number(q.subsidy)>Number(q.cost))e.push('Estimated subsidy must be between zero and total cost.');if(!Array.isArray(q.payments)||q.payments.length!==3||q.payments.some(x=>!numeric(x)||Number(x)<0||Number(x)>100)||Math.abs(q.payments.reduce((a,b)=>a+Number(b),0)-100)>0.000001)e.push('Payment percentages must total 100.');if(!q.referenceReviewed)e.push('Review and confirm reference values before saving or sending.');if(!numeric(q.validity)||Number(q.validity)<=0)e.push('Enter a positive validity period.');const parts=Array.isArray(q.equipment)?equipmentRows(q.equipment):[];if(!parts.length)e.push('Include at least one equipment item.');for(const part of parts){if(!String(part.name||'').trim())e.push(`Enter particulars for equipment group ${part.groupIndex+1}.`);if(!String(part.description||'').trim())e.push(`Enter item / specification for group ${part.groupIndex+1}, item ${part.itemIndex+1}.`);}return e;}
function amounts(q){return {vendorDue:Number(q.cost),net:Number(q.cost)-Number(q.subsidy)};}
function checkState(data){
 const bad=()=>{throw Error('Invalid backup: expected a Nav Bharat v1 backup with complete quotation data.');};
 if(!data||typeof data!=='object')bad();data=clone(data);for(const definition of [data.settings,data.draft,...(Array.isArray(data.quotes)?data.quotes:[])])if(Array.isArray(definition?.equipment))definition.equipment=normalizeEquipment(definition.equipment);
 const shape=(x,t,partial=false)=>{if(Array.isArray(t))return Array.isArray(x)&&x.length<1000&&x.every(v=>shape(v,t[0],partial));if(t!==null&&typeof t==='object')return x&&typeof x==='object'&&!Array.isArray(x)&&Object.keys(t).every(k=>shape(x[k],t[k],partial));return (partial&&typeof t==='number'&&x==='')||(typeof x===typeof t&&(typeof x!=='number'||Number.isFinite(x))&&(typeof x!=='string'||x.length<=50000));};
 if(!data||data.version!==1||!Number.isSafeInteger(data.next)||data.next<1||!shape(data.settings,defaults())||!Array.isArray(data.quotes)||data.quotes.length>10000)bad();
 const template=newQuote(defaults(),1);delete template.equipmentState;if(data.quotes.some(q=>!shape(q,template)||!q.id||validate(q).length))bad();if(data.draft!==null&&(!shape(data.draft,template,true)||data.draft.payments.length!==3))bad();
 for(const q of [...data.quotes,...(data.draft?[data.draft]:[])]){if(q.equipmentState!==undefined){const m=q.equipmentState;if(!m||typeof m!=='object'||!shape(m.baseline,defaults().equipment)||typeof m.priceChecked!=='string'||m.priceChecked.length>2000000)bad();}ensureEquipmentState(q);}
 const sample=newQuote(data.settings,1);sample.customer.name='Check';sample.customer.address='Check';sample.referenceReviewed=true;if(validate(sample).length)bad();
 if(new Set(data.quotes.map(q=>q.id)).size!==data.quotes.length||new Set(data.quotes.map(q=>q.number)).size!==data.quotes.length)bad();return clone(data);
}
class Store {
 constructor(storage){this.storage=storage;this.state={version:1,next:1,settings:defaults(),quotes:[],draft:null};const raw=storage.getItem('navbharat.v1');if(raw)this.state=checkState(JSON.parse(raw));}
 backup(){return JSON.stringify(this.state,null,2);}
 restore(json,confirmed){const data=checkState(JSON.parse(json));if(!confirmed)return false;this.storage.setItem('navbharat.v1',JSON.stringify(data));this.state=data;return true;}
 persist(){this.storage.setItem('navbharat.v1',JSON.stringify(this.state));}
 allocateNumber(){const year=new Date().getFullYear();let number;do{number=`${this.state.next++}/${year}`;}while(this.state.quotes.some(q=>q.number===number));return number;}
 create(){const q=newQuote(this.state.settings,1);q.number=this.allocateNumber();this.persist();return q;}
 draft(q){this.state.draft=clone(q);this.persist();}
 save(q){const errors=validate(q);if(errors.length)throw Error(errors.join('\n'));if(this.state.quotes.some(x=>x.number===q.number&&x.id!==q.id))throw Error('Quotation number already exists.');if(!q.id)q.id=globalThis.crypto?.randomUUID?.()||`q-${Date.now()}-${Math.random().toString(36).slice(2)}`;const index=this.state.quotes.findIndex(x=>x.id===q.id);if(index<0)this.state.quotes.push(clone(q));else this.state.quotes[index]=clone(q);this.state.draft=clone(q);this.persist();return q;}
 open(id){const q=this.state.quotes.find(q=>q.id===id);if(!q)throw Error('Quotation not found.');return clone(q);}
 duplicate(q){const n=clone(q);ensureEquipmentState(n).baseline=normalizeEquipment(n.equipment);n.id='';n.number=this.allocateNumber();n.date=localDate();n.customer=newQuote(this.state.settings,1).customer;n.referenceReviewed=false;this.draft(n);return n;}
 remove(id,confirmed){if(!confirmed)return false;this.state.quotes=this.state.quotes.filter(q=>q.id!==id);if(this.state.draft?.id===id)this.state.draft=null;this.persist();return true;}
}
function useTestBank(q){Object.assign(q.company,{ifsc:'TEST0000001',account:'0000000000',bankName:'TEST ONLY - NOT FOR PAYMENT',bankVerified:false});return q;}
return {priceNeedsReview,acknowledgePrice,ensureEquipmentState,equipmentChanged,clone,localDate,defaults,newQuote,validate,amounts,Store,useTestBank,normalizeEquipment,equipmentRows};
});
